services:
  ntskelbimusistemasaitynai:
    image: ${DOCKER_REGISTRY-}ntskelbimusistemasaitynai
    build:
      context: .
      dockerfile: NTSkelbimuSistemaSaitynai/Dockerfile
    restart: unless-stopped
  db:
    build:
      context: .
      dockerfile: PGSQLDockerfile
    restart: unless-stopped

