services:
  ntskelbimusistemasaitynai:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS_FILE=/run/secrets/dbpass
      - DB_NAME=postgres
    ports:
      - "8080:8080"
    networks:
      - bridged
      - dbnet
    secrets:
      - dbpass
      - config
  db:
    networks:
#      - bridged
      - dbnet
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/dbpass
    secrets:
      - dbpass

networks:
  bridged:
    internal: false
  dbnet:
    internal: true
secrets:
  dbpass:
    file: secrets/pgpass.txt
  config: 
    file: secrets/config.json
volumes:
  dbdata:
    external: false  