services:
  ntskelbimusistemasaitynai:
    image: ${DOCKER_REGISTRY-}ntskelbimusistemasaitynai
    build:
      context: .
      dockerfile: NTSkelbimuSistemaSaitynai/Dockerfile
  db:
    build:
      context: .
      dockerfile: PGSQLDockerfile

